### PR TITLE
Adding boilerplate files as an examble branch

### PR DESCRIPTION
**Pull request by CNSabers**
added a few files to see how creating pull request works

### CODE REVIEW

**Comment by CNSabers** [comment]
Hey, this is a comment about my branch!

**Comment by kincaidoneil** [comment]
Hello, world.

**Comment by kincaidoneil** [comment]
Are you sure about that...?

**Comment by CNSabers** [comment]
About what?

**Comment by kincaidoneil** [comment]
I meant about assigning it to me... haha. Disregard.

**Comment by CNSabers** [comment]
haha

**Pull request merged**
